USE StudentDB;
GO

CREATE TABLE Students
(
    StudentId INT IDENTITY(1,1) PRIMARY KEY,

    Name NVARCHAR(100) NOT NULL,

    Email NVARCHAR(150) NOT NULL UNIQUE,

    Age INT NOT NULL,

    Course NVARCHAR(100) NOT NULL,

    City NVARCHAR(100) NOT NULL,

    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
GO